[package]
name = "aa_tutorial"
version.workspace = true
edition = "2023_11"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
snforge_std.workspace = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.25.0" }

[scripts]
test.workspace = true

[[target.starknet-contract]]
casm = true
